/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4_canhan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lab4_canhan.SHA1;

/**
 *
 * @author Admin
 */
public class addUser extends javax.swing.JFrame {

    Vector nv = new Vector();
    Vector datanv = new Vector();

   

//    public static String setMALOP(){
//        return LOGIN.getMALOP();
//    }
    @SuppressWarnings("unchecked")

    public addUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        nv.add("MANV");
        nv.add("HOTEN");
        nv.add("EMAIL");
        nv.add("LUONG");
        nv.add("TENDN");
        nv.add("MATKHAU");

        tableqlnv.setModel(new DefaultTableModel(datanv, nv));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableqlnv = new javax.swing.JTable();
        jLabelTen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        jLabelPass = new javax.swing.JLabel();
        JlableUser = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JPasswordField();
        txttenDN = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        jLabelGioiTinh = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        jLabelHo = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jlableIDNV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm Nhân Viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableqlnv.setBackground(new java.awt.Color(102, 102, 102));
        tableqlnv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tableqlnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MANV", "HOTEN", "EMAIL", "LUONG", "TENDN", "MATKHAU"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableqlnv.setRowHeight(30);
        tableqlnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableqlnvKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableqlnv);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 680, 530));

        jLabelTen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTen.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTen.setText("EMAIL");
        getContentPane().add(jLabelTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 650, 92, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setBackground(new java.awt.Color(51, 255, 51));
        insert.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/add-user-302 (1).png"))); // NOI18N
        insert.setText("Ghi/lưu");
        insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertMouseClicked(evt);
            }
        });
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 130, -1));

        jLabelPass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPass.setText("MATKHAU");
        jPanel1.add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        JlableUser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JlableUser.setForeground(new java.awt.Color(0, 0, 0));
        JlableUser.setText("TENDN");
        jPanel1.add(JlableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        txtmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatkhauActionPerformed(evt);
            }
        });
        jPanel1.add(txtmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 246, 40));

        txttenDN.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txttenDN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttenDNFocusLost(evt);
            }
        });
        jPanel1.add(txttenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 246, -1));

        txtluong.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtluong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtluongFocusLost(evt);
            }
        });
        jPanel1.add(txtluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 246, -1));

        jLabelGioiTinh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelGioiTinh.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGioiTinh.setText("LUONG");
        jPanel1.add(jLabelGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 246, -1));

        txthoten.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txthoten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txthotenFocusLost(evt);
            }
        });
        jPanel1.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 246, -1));

        jLabelHo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelHo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHo.setText("HOTEN");
        jPanel1.add(jLabelHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 246, 40));

        jlableIDNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlableIDNV.setForeground(new java.awt.Color(0, 0, 0));
        jlableIDNV.setText("MANV");
        jPanel1.add(jlableIDNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 580, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên vừa thêm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 740, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // them
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed

//        String idtam = txtid.getText();
//        String tamid;
//        try {
//            Class.forName(driver);
//            Connection conid = DriverManager.getConnection(url, user, password);
//            String sqlus = "SELECT MANV FROM NHANVIEN";
//            Statement stid = conid.createStatement();
//            ResultSet rsid = stid.executeQuery(sqlus);
//            while (rsid.next()) {
//                tamid = rsid.getString("MANV");
//                if (tamid.equals(idtam)) {
//                    JOptionPane.showMessageDialog(this, "MANV đã tồn tại xin nhập lại");
//                    return;
//                }
//
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        if (txtid.getText().equals("") || txthoten.getText().equals("") || txtemail.getText().equals("") || txtluong.getText().equals("")
//                || txttenDN.getText().equals("") || txtmatkhau.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Không để thông tin trống");
//            return;
//        }
//        int dk = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng ký không", "Confirm", JOptionPane.YES_NO_OPTION);
//        if (dk != JOptionPane.YES_NO_OPTION) {
//            return;
//        }
//        String usertam = txttenDN.getText();
//        String tam;
//        try {
//            Class.forName(driver);
//            Connection con1 = DriverManager.getConnection(url, user, password);
//            String sqlus = "SELECT TENDN FROM NHANVIEN";
//            Statement stus = con1.createStatement();
//            ResultSet rsus = stus.executeQuery(sqlus);
//            while (rsus.next()) {
//                tam = rsus.getString("TENDN");
//                if (tam.equals(usertam)) {
//                    JOptionPane.showMessageDialog(this, "Username đã tồn tại xin nhập lại");
//                    return;
//                }
//
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
        try {
            String manv = txtid.getText();
            String hoten = txthoten.getText();
            String email = txtemail.getText();
            String luong = AES256.encrypt(txtluong.getText());
            String tendn = txttenDN.getText();
            String matkhau = SHA1.encryptPassword(txtmatkhau.getText());
            System.out.println(matkhau);          
            String sql = "EXEC SP_INS_ENCRYPT_NHANVIEN '" + manv + "', '" + hoten + "', '" + email + "', '" + luong + "', '" + tendn + "', '" + matkhau + "'";
            DBAccess db = new DBAccess();
            int kq = db.Update(sql);
            if (kq != 0) {
                JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String MANV = txtid.getText();
        String HOTEN = txthoten.getText();
        String MAIL = txtemail.getText();
        String LUONG = txtluong.getText();
        String TENDN = txttenDN.getText();
        String MATKHAU = txtmatkhau.getText();

        Vector add = new Vector(); // tao lop de them du lieu
        add.add(MANV);
        add.add(HOTEN);
        add.add(MAIL);
        add.add(LUONG);
        add.add(TENDN);
        add.add(MATKHAU);
        datanv.add(add); // luu du lieu vao add
        tableqlnv.setModel(new DefaultTableModel(datanv, nv));
    }//GEN-LAST:event_insertActionPerformed

    private void insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseClicked
        desplaydetails(((JTable) evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_insertMouseClicked

    private void tableqlnvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableqlnvKeyReleased
        desplaydetails(((JTable) evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_tableqlnvKeyReleased

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

// bat kieu dien k de trong thong tin
    private void txthotenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txthotenFocusLost
//        String ho=txtho.getText();
//        if(ho.length()>0){
//            
//        }else{
//            JOptionPane.showMessageDialog(rootPane,"Không để họ trống!");
//        }
    }//GEN-LAST:event_txthotenFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
//         String ten=txtten.getText();
//        if(ten.length()>0){
//             
//        }
//        else{
//            JOptionPane.showMessageDialog(rootPane,"Không để tên trống!");
//        }

    }//GEN-LAST:event_txtemailFocusLost

    private void txtluongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtluongFocusLost
//        String gioitinh=txtgioitinh.getText();
//        if(gioitinh.length()>0){
//            
//        }else{
//            JOptionPane.showMessageDialog(rootPane,"Không để giới tính trống!");
//        }

    }//GEN-LAST:event_txtluongFocusLost

    private void txttenDNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttenDNFocusLost
//       String username=txtuser.getText();
//        if(username.length()>0){
//            
//        }else{
//            JOptionPane.showMessageDialog(rootPane,"Không để username trống!");
//        }
    }//GEN-LAST:event_txttenDNFocusLost

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        String id = txtid.getText();
        String reg = "^\\w{2}\\d{2}$";
        if (id.length() > 0) {
            if (!id.matches(reg)) // neu id sai dinh dang la 2 chu 4 so
            {
                JOptionPane.showMessageDialog(rootPane, "Sai định dạng Id, Nhập lại,NV0001->NV9999");
            }
//            txtid.requestFocus();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Không để Mã nhân viên trống!");
//            txtid.requestFocus();
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatkhauActionPerformed

    private void desplaydetails(int selectedRows) {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlableUser;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelGioiTinh;
    private javax.swing.JLabel jLabelHo;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelTen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlableIDNV;
    private javax.swing.JTable tableqlnv;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtluong;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txttenDN;
    // End of variables declaration//GEN-END:variables
}
